### ISSUE TITLE
Very criptic documentation

### ISSUE THREAD

**Issue by didaquis** [dtslvr/cogear-theme-ejs-bootstrap-blog#1]
HI. Can you provide more detailed documentation?

I installed Cogear. Then I installed https://github.com/codemotion/cogear-plugin-blog and then I followed instructions of this repo. 

Finally i run command `cogear` on my project and CLI throws an error:
```
✔ Current working dir: ~/repos/cogear-example
✔ Theme ejs-bootstrap-blog.
✔ Preloaded in 42ms.
✔ Resources are linked.
(node:50783) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:1158:7)
    at Promise.all.files.map.file (/usr/local/lib/node_modules/cogear/node_modules/hard-source-webpack-plugin/lib/envHash.js:42:54)
    at Array.map (<anonymous>:null:null)
    at hashFiles (/usr/local/lib/node_modules/cogear/node_modules/hard-source-webpack-plugin/lib/envHash.js:42:28)
    at module.exports.options (/usr/local/lib/node_modules/cogear/node_modules/hard-source-webpack-plugin/lib/envHash.js:84:20)
    at runReadOrReset (/usr/local/lib/node_modules/cogear/node_modules/hard-source-webpack-plugin/index.js:286:9)
    at _promise0.then._result0 (<anonymous>:15:17)
    at <anonymous>:null:null

(node:50783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by dtslvr** [comment]
Hi @didaquis,

Thanks for your interest in this project. It looks like a path is not correct. Can you please share your `config.yaml`?

I have created a [preset](https://github.com/dtslvr/cogear-preset-ejs-bootstrap-blog) for the `ejs-bootstrap-blog` theme. Maybe it can give you an idea of the setup.

**Comment by didaquis** [comment]
Thanks for your help. I'm out of home for some weeks. I will give another try when I come back home. 

> I have created a preset for the ejs-bootstrap-blog theme

Thanks!
